/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ifengyu_tcpserver_jni_OpusUtils */

#ifndef _Included_com_ifengyu_tcpserver_jni_OpusUtils
#define _Included_com_ifengyu_tcpserver_jni_OpusUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ifengyu_tcpserver_jni_OpusUtils
 * Method:    createEncoder
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_ifengyu_tcpserver_jni_OpusUtils_createEncoder
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_ifengyu_tcpserver_jni_OpusUtils
 * Method:    createDecoder
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_com_ifengyu_tcpserver_jni_OpusUtils_createDecoder
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_ifengyu_tcpserver_jni_OpusUtils
 * Method:    encode
 * Signature: (J[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_ifengyu_tcpserver_jni_OpusUtils_encode
  (JNIEnv *, jclass, jlong, jshortArray, jint, jbyteArray);

/*
 * Class:     com_ifengyu_tcpserver_jni_OpusUtils
 * Method:    decode
 * Signature: (J[B[S)I
 */
JNIEXPORT jint JNICALL Java_com_ifengyu_tcpserver_jni_OpusUtils_decode
  (JNIEnv *, jclass, jlong, jbyteArray, jshortArray);

/*
 * Class:     com_ifengyu_tcpserver_jni_OpusUtils
 * Method:    destroyEncoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ifengyu_tcpserver_jni_OpusUtils_destroyEncoder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ifengyu_tcpserver_jni_OpusUtils
 * Method:    destroyDecoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ifengyu_tcpserver_jni_OpusUtils_destroyDecoder
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
